[mod] [file] BUG #939 【文件管理】DialogException SimpleFileListFragment.java:161
java.lang.RuntimeException: Unable to destroy activity {imoblife.toolbox.full/com.filemanager.FileManagerActivity}: com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3870)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3888)
	at android.app.ActivityThread.access$1500(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5536)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
Caused by: com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
	at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1199)
	at base.util.FileUtils.showStorageAccessDialog(FileUtils.java:637)
	at com.filemanager.lists.SimpleFileListFragment.onViewCreated(SimpleFileListFragment.java:161)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
	at android.support.v4.app.FragmentManagerImpl.dispatchReallyStop(FragmentManager.java:1956)
	at android.support.v4.app.FragmentActivity.onReallyStop(FragmentActivity.java:790)
	at android.support.v4.app.FragmentActivity.doReallyStop(FragmentActivity.java:767)
	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:314)
	at base.util.ui.track.BaseTrackFragmentActivity.onDestroy(BaseTrackFragmentActivity.java:19)
	at android.app.Activity.performDestroy(Activity.java:6172)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1146)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3857)
	... 10 more