file: 修改报错
java.lang.RuntimeException: Unable to get provider
com.filemanager.FileManagerProvider:
android.content.res.Resources$NotFoundException: Resource ID #0x7f060001
at android.app.ActivityThread.installProvider(ActivityThread.java:5236)
at
android.app.ActivityThread.installContentProviders(ActivityThread.java:4828)
at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711)
at android.app.ActivityThread.access$1600(ActivityThread.java:175)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5602)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: Resource ID
#0x7f060001
at android.content.res.Resources.getValue(Resources.java:2350)
at
android.content.res.Resources.loadXmlResourceParser(Resources.java:3668)
at android.content.res.Resources.getXml(Resources.java:2215)
at
com.filemanager.FileManagerProvider.getMimeTypes(FileManagerProvider.java:46)
at
com.filemanager.FileManagerProvider.onCreate(FileManagerProvider.java:33)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
at android.app.ActivityThread.installProvider(ActivityThread.java:5233)
... 12 more