[fix] FormatFlagsConversionMismatchException SimpleAnalysisListFragment.java:448
java.util.FormatFlagsConversionMismatchException: %s does not support ' '
	at java.util.Formatter$FormatToken.checkFlags(Formatter.java:1359)
	at java.util.Formatter.transform(Formatter.java:1440)
	at java.util.Formatter.doFormat(Formatter.java:1079)
	at java.util.Formatter.format(Formatter.java:1040)
	at java.util.Formatter.format(Formatter.java:1009)
	at java.lang.String.format(String.java:1988)
	at android.content.res.Resources.getString(Resources.java:350)
	at android.support.v4.app.Fragment.getString(Fragment.java:655)
	at com.filemanager.occupancy.SimpleAnalysisListFragment$ConfirmDialog.<init>(SimpleAnalysisListFragment.java:448)
	at com.filemanager.occupancy.SimpleAnalysisListFragment$DeleteDialog.onSelection(SimpleAnalysisListFragment.java:435)
	at com.afollestad.materialdialogs.MaterialDialog.onItemClick(MaterialDialog.java:184)
	at android.widget.AdapterView.performItemClick(AdapterView.java:298)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1128)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2812)
	at android.widget.AbsListView$1.run(AbsListView.java:3571)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

	https://play.google.com/apps/publish/?dev_acc=17736375203683117254#ErrorClusterDetailsPlace:p=imoblife.toolbox.full&et=CRASH&lr=LAST_7_DAYS&ecn=java.util.FormatFlagsConversionMismatchException&tf=Formatter.java&tc=java.util.Formatter$FormatToken&tm=checkFlags&nid&an&c&s=reports_last_week_desc